"use client";

import { useMemo, useState } from "react";
import { Camera, CheckCircle2, MonitorOff, Radio } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import type { DemoCamera, DemoPlant } from "@/lib/greenhouse-demo-store";

export type AiDetectionViewProps = { plant: DemoPlant; cameras: DemoCamera[]; reviewedCameraIds: string[]; onSave: (cameraId: string) => void };

export function AiDetectionView({ plant, cameras, reviewedCameraIds, onSave }: AiDetectionViewProps) {
  const initialCameraId = useMemo(() => cameras.find((camera) => camera.zone === plant.zone && camera.enabled)?.id ?? cameras.find((camera) => camera.enabled)?.id ?? cameras[0]?.id ?? "", [cameras, plant.zone]);
  const [selectedCameraId, setSelectedCameraId] = useState(initialCameraId);
  const selectedCamera = cameras.find((camera) => camera.id === selectedCameraId) ?? cameras.find((camera) => camera.id === initialCameraId) ?? cameras[0];
  if (!selectedCamera) return <Card><CardContent className="py-10 text-center text-muted-foreground">ยังไม่มีกล้องในโรงเรือนนี้ กรุณาเพิ่มและเปิดใช้งานกล้องจากหน้าการตั้งค่า</CardContent></Card>;
  const unavailable = !selectedCamera.enabled || selectedCamera.status === "offline";
  const reviewed = reviewedCameraIds.includes(selectedCamera.id);

  return <div className="space-y-6">
    <Card className="shadow-none"><CardHeader className="border-b border-border/70 pb-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="page-kicker">หลักฐานและโมเดล</p><h2 className="mt-1 font-semibold">แหล่งภาพสำหรับ AI</h2><p className="mt-1 text-sm text-muted-foreground">เลือกดูหลักฐานและผลวิเคราะห์แยกตามกล้อง</p></div><Badge variant="outline">รอข้อมูลภาพ</Badge></div></CardHeader><CardContent className="pt-1"><div className="grid gap-2 md:grid-cols-3" role="radiogroup" aria-label="เลือกกล้อง"><span className="sr-only">เลือกกล้อง</span>{cameras.map((camera) => { const selected = camera.id === selectedCamera.id; const usable = camera.enabled && camera.status === "online"; return <button type="button" key={camera.id} role="radio" aria-checked={selected} onClick={() => setSelectedCameraId(camera.id)} className={`min-h-20 rounded-xl border p-3 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${selected ? "border-primary bg-primary/[0.06]" : "border-transparent bg-muted/45 hover:border-border hover:bg-muted/70"}`}><span className="flex items-center justify-between gap-2"><span className="grid size-8 place-items-center rounded-lg bg-card text-muted-foreground"><Camera className="size-4" aria-hidden="true" /></span><Badge variant={usable ? "secondary" : "outline"} className={usable ? "text-primary" : "text-muted-foreground"}>{usable ? "ออนไลน์" : camera.enabled ? "ออฟไลน์" : "ปิดใช้งาน"}</Badge></span><strong className="mt-2 block text-sm">{camera.name}</strong><span className="mt-1 block text-xs text-muted-foreground">{camera.id} · {camera.zone}</span></button>; })}</div><p className="mt-4 flex gap-2 border-t border-border/70 pt-4 text-sm text-muted-foreground"><Radio className="mt-0.5 size-4 shrink-0" aria-hidden="true" />รองรับการจัดการหลายกล้องแล้ว แต่จะวิเคราะห์ได้เมื่อเชื่อมต่อ webcam, RTSP หรือกล้องจริง</p></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(22rem,.75fr)]"><Card className="overflow-hidden shadow-none"><CardHeader className="flex-row items-start justify-between gap-3"><div><p className="page-kicker">หลักฐานล่าสุด</p><h2 className="mt-1 font-semibold">ภาพจาก {selectedCamera.name}</h2><p className="mt-1 text-sm text-muted-foreground">{selectedCamera.zone}</p></div><Badge variant="outline">{selectedCamera.source}</Badge></CardHeader><CardContent className="p-0"><div className="grid aspect-[16/10] place-items-center bg-muted p-6 text-center"><div><MonitorOff className="mx-auto size-9 text-muted-foreground" aria-hidden="true" /><strong className="mt-3 block">ยังไม่มีภาพที่บันทึก</strong><p className="mt-1 text-sm text-muted-foreground">{unavailable ? "เปิดใช้งานกล้องและตรวจสอบ gateway ก่อนเริ่มวิเคราะห์" : "รอภาพจริงจากกล้องนี้ก่อน จึงจะแสดงหลักฐานและผลวิเคราะห์"}</p></div></div><div className="grid gap-1 border-t p-4 text-sm sm:grid-cols-2"><span><strong>{selectedCamera.id}</strong><small className="block text-muted-foreground">{selectedCamera.captureInterval} · {selectedCamera.status === "online" ? "พร้อมรับภาพ" : "ไม่พร้อมวิเคราะห์"}</small></span><span><strong>ยังไม่มีเวลาที่บันทึก</strong><small className="block text-muted-foreground">ไม่มีหลักฐานภาพสำหรับการแสดงผล</small></span></div></CardContent></Card>
      <Card><CardHeader className="flex-row items-start justify-between gap-3"><div><h2 className="font-semibold">สรุปผลการวิเคราะห์</h2><p className="text-sm text-muted-foreground">เชื่อมกับภาพจาก {selectedCamera.id}</p></div><Badge variant="outline">รอภาพ</Badge></CardHeader><CardContent className="space-y-5"><div className="rounded-lg bg-muted p-4 text-sm text-muted-foreground">เมื่อกล้องบันทึกภาพจริง ระบบจะแสดงความมั่นใจ หลักฐาน และขั้นตอนถัดไปของภาพนี้โดยไม่ใช้ผลตัวอย่าง</div><div className="rounded-lg bg-secondary p-4"><strong>ขั้นตอนถัดไป</strong><p className="mt-1 text-sm text-muted-foreground">ตรวจการเชื่อมต่อของ {selectedCamera.name} แล้วถ่ายภาพเพื่อเริ่มวิเคราะห์</p></div><Button className="min-h-11 w-full" onClick={() => onSave(selectedCamera.id)} disabled><CheckCircle2 aria-hidden="true" />รอภาพจากกล้อง</Button></CardContent></Card>
    </div>
  </div>;
}
