"use client";

import { useState } from "react";
import { ArrowDownToLine, CalendarDays, ChartNoAxesCombined, Droplets, Thermometer, TrendingUp } from "lucide-react";
import { PageTitle } from "@/components/ui/page-title";

export function AnalyticsView() {
  const [period, setPeriod] = useState("7 days");
  return <div className="page-stack"><PageTitle eyebrow="Insights · data complete" title="Analytics" subtitle="Compare environmental trends with AI detections and device activity." actions={<button className="button secondary"><ArrowDownToLine size={17} /> Export CSV</button>} />
    <section className="analytics-toolbar panel"><div className="filter-tabs">{["Today", "7 days", "30 days"].map((item) => <button key={item} className={period === item ? "active" : ""} onClick={() => setPeriod(item)}>{item}</button>)}</div><button className="button secondary"><CalendarDays size={16} /> Custom range</button></section>
    <section className="analytics-summary"><article><Thermometer /><span><small>Average temperature</small><strong>27.8°C</strong><em>+0.6% vs previous</em></span></article><article><Droplets /><span><small>Average soil moisture</small><strong>45.2%</strong><em>−2.4% vs previous</em></span></article><article><TrendingUp /><span><small>Plant health rate</small><strong>88%</strong><em>Stable this period</em></span></article></section>
    <article className="analytics-chart panel"><div className="panel-heading"><div><span className="section-kicker">ENVIRONMENT HISTORY</span><h3>Temperature and humidity · {period}</h3></div><span className="model-status"><ChartNoAxesCombined size={15} /> Hourly averages</span></div><div className="large-chart" role="img" aria-label="Environmental trend chart"><div className="chart-guides"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 900 310" preserveAspectRatio="none"><path className="analytics-area" d="M0 225 C110 210 140 120 245 145 S390 205 470 140 S600 70 680 120 S800 185 900 105 L900 310 L0 310Z"/><path className="line temp-line" d="M0 225 C110 210 140 120 245 145 S390 205 470 140 S600 70 680 120 S800 185 900 105"/><path className="line humid-line" d="M0 105 C100 75 180 105 260 90 S410 65 500 92 S660 150 740 132 S820 85 900 96"/></svg><div className="event-marker marker-one"><i />Irrigation</div><div className="event-marker marker-two"><i />Ventilation</div><div className="chart-axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></article>
    <section className="summary-grid"><article className="panel insight-card"><span className="status-pill healthy">Positive pattern</span><h3>Morning ventilation improves stability</h3><p>Temperature variation decreased by 18% during days with a 09:00 ventilation cycle.</p></article><article className="panel insight-card"><span className="status-pill warning">Watch soil moisture</span><h3>Zone B dries faster after 14:00</h3><p>Consider a short afternoon irrigation rule when moisture drops below 35%.</p></article></section>
  </div>;
}
